### ISSUE TITLE
System.Private.CoreLib: Could not load the specified file.

### ISSUE THREAD

**Issue by ChaunceyJ** [Jtango18/AZ-1717-Repro#1]
hi, I found the original problem 'System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.' was caused by setting wrong Microsoft.NET.Sdk.Functions's version like the following. 

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
  </ItemGroup>
```

So I changed it to 3.0.9. It fixed but a new error occurred. When I run your code, it also happened.

> [2020/10/22 上午9:32:13] Executed 'Repro1717' (Failed, Id=1206acf7-fe09-4fec-803e-8a9f21254a1b)
[2020/10/22 上午9:32:13] System.Private.CoreLib: Exception while executing function: Repro1717. Microsoft.Data.SqlClient: Could not load file or assembly 'System.Memory, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
[2020/10/22 上午9:32:13] . System.Private.CoreLib: Could not load the specified file.

I am trying to add the package 'System.Memory, Version=4.2.1.0'  into the project like the following. But it doesn't work. 

```xml
 <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.1" />
    <PackageReference Include="System.Memory" Version="4.2.1.0" />
  </ItemGroup>
```

Would you please tell me how to fix it or whether it is a bug? Thank you so much.🙏

**Comment by Jtango18** [comment]
I'll have look at this over the next day or two and see if we can figure it out.

**Comment by Jtango18** [comment]
Are you able to submit a Pull Request to this code showing what you're trying to do? I can't seem to break it. What code do you added to have that error happen.

**Comment by ChaunceyJ** [comment]
I just used SqlConnectionStringBuilder to generate connection string to replace the original connect string. Then when I.connect the SQL Server the error happened. And the PR link is [https://github.com/Jtango18/AZ-1717-Repro/pull/2](https://github.com/Jtango18/AZ-1717-Repro/pull/2). Thank you so much.

**Comment by Jtango18** [comment]
I just tried the code, and I can't replicate. It's not clear why you're adding System.Memory.
